# next.js docker-compose.yml
services:
  app:
    build:
      context: .
    tty: true
    volumes:
      - ./src:/app
    environment:
      - WATCHPACK_POLLING=true
      - NEXT_PUBLIC_API_URL=https://my-rails-api.fly.dev # Docker内部のRails APIのURLを設定
    command: sh -c "npm run dev"
    ports:
      - "3000:3000"
    networks:
      - myapp_network

networks:
  myapp_network:
    external: true
